### PR TITLE
AST-3169: updated docs for patientPathways query

### PR DESCRIPTION
**Pull request by nckhell**
- https://awellhealth.atlassian.net/browse/AST-3169
- https://awellhealth.atlassian.net/browse/AST-3210
- https://awellhealth.atlassian.net/browse/AST-3209
- https://awellhealth.atlassian.net/browse/AST-3208

### CODE REVIEW

**Comment by nckhell** [comment]
@rahulkeerthi Open for review.

**To check:**
- `revision` is renamed to `version`
- https://awellhealth.atlassian.net/browse/AST-3208 is not implemented yet? Wasn't able to find anything in the code base about additional filter params for this query

**Comment by rahulkeerthi** [comment]
> @rahulkeerthi Open for review.
> 
> **To check:**
> 
> * `revision` is renamed to `version`
> * https://awellhealth.atlassian.net/browse/AST-3208 is not implemented yet? Wasn't able to find anything in the code base about additional filter params for this query

I took a look at the history for AST-3208 and either there was some miscommunication or misunderstanding, but certainly the ticket was closed with something similar but unrelated being delivered in that MR. Will look into how this happened but I'm merging an MR so both of the above are in there now.

**Review by rahulkeerthi — APPROVED** [review]
With the filter for status, the query would be used this way:

```graphql
query GetPatientPathways(
    $patient_id: String!
    $status: [String!]
    ) {
  patientPathways(
      patient_id: $patient_id
      filters: {
        status: { in: $status }
      }
    ) {
        patientPathways {
              ....
      }
    }
```

Feel free to include it this way if you intend to have the base queries show filtering (as we discussed, I'll leave it up to you so this could just be an FYI).

**Comment by rahulkeerthi** [comment]
@nckhell 
Also a general point (will repeat it elsewhere so you don't miss it) but general logic we intend to apply is that if you provide an empty array for a filter (like status) then we will 'disable' that filter (similar in logic to how unchecking all the filters in the activity feed shows all the activities, not zero activities). We don't do the same for strings though, e.g. "" for a pathway_id will return an error as nothing is found. 

Let me know if you think this behaviour will generate surprise for the API user.

**Comment by nckhell** [comment]
@rahulkeerthi updated the documentation with the filters.

**Comment by nckhell** [comment]
@rahulkeerthi can you do a final review and approve? Thay way we can merge this one. Special attention for the type I've used for the filters: `FilterPatientPathwaysGraphqlType` (might be incorrect).

**Pull request merged**
